package ${basePackage};

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Smoke-test integration test for the {@code ${entityName}} REST endpoints.
 *
 * <p>Generated by Umaboot. Covers the bare minimum that the controller wires up
 * end-to-end against a real database (provided by {@link AbstractIntegrationTest}'s
 * Testcontainer). Extend with domain-specific assertions as needed.</p>
 *
 * <p><b>Note:</b> this test requires Docker to be running locally.</p>
 */
@SpringBootTest
@AutoConfigureMockMvc
class ${entityName}IntegrationTest extends AbstractIntegrationTest {

    @Autowired
    MockMvc mvc;

    @Test
    void contextLoads() {
        // The Spring context starts cleanly with the configured database container.
        // If this test fails, check Docker is running and the container could start.
    }

    @Test
    void list_returnsOk() throws Exception {
        mvc.perform(get("/api/${entityVar}s"))
                .andExpect(status().isOk());
    }

    @Test
    void getById_unknownId_returns404() throws Exception {
        mvc.perform(get("/api/${entityVar}s/{id}", ${unknownIdLiteral}))
                .andExpect(status().isNotFound());
    }
}
