package ${basePackage}.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Service;

import java.nio.charset.StandardCharsets;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;
import javax.crypto.SecretKey;

/**
 * JWT issuer + parser (HS256). Generated by Umaboot.
 *
 * <p>The signing key comes from {@code umaboot.security.jwt.secret} in
 * application config — the generated default is a placeholder. <b>Replace
 * before deploying</b>: externalize via the {@code SPRING_SECURITY_JWT_SECRET}
 * environment variable, AWS Secrets Manager, Vault, etc.</p>
 *
 * <p>HS256 expects at least 256 bits / 32 bytes of secret material; shorter
 * secrets will fail at startup.</p>
 */
@Service
public class JwtTokenService {

    private final SecretKey signingKey;
    private final long expirationMillis;

    public JwtTokenService(@Value("${r"${umaboot.security.jwt.secret}"}") String secret,
                           @Value("${r"${umaboot.security.jwt.expiration-minutes:60}"}") long expirationMinutes) {
        this.signingKey = Keys.hmacShaKeyFor(secret.getBytes(StandardCharsets.UTF_8));
        this.expirationMillis = expirationMinutes * 60_000L;
    }

    /** Issue a token for the authenticated user. */
    public String issue(UserDetails user) {
        long now = System.currentTimeMillis();
        List<String> roles = user.getAuthorities().stream()
                .map(GrantedAuthority::getAuthority)
                .collect(Collectors.toList());
        return Jwts.builder()
                .setSubject(user.getUsername())
                .claim("roles", roles)
                .setIssuedAt(new Date(now))
                .setExpiration(new Date(now + expirationMillis))
                .signWith(signingKey, SignatureAlgorithm.HS256)
                .compact();
    }

    /** Returns the JWT claims if the token is valid; throws otherwise. */
    public Claims parse(String token) {
        return Jwts.parserBuilder()
                .setSigningKey(signingKey)
                .build()
                .parseClaimsJws(token)
                .getBody();
    }

    /** Convenience: extract the username from a token without other claims. */
    public String usernameOf(String token) {
        return parse(token).getSubject();
    }
}
