package ${basePackage}.config;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.servers.Server;
import org.springframework.context.annotation.Configuration;

/**
 * springdoc-openapi configuration.
 *
 * <p>With the springdoc OpenAPI UI dependency on the classpath,
 * Spring Boot serves:</p>
 * <ul>
 *   <li><b>{@code /v3/api-docs}</b> — the live OpenAPI 3 spec (JSON).</li>
 *   <li><b>{@code /swagger-ui.html}</b> — interactive Swagger UI to browse/try the API.</li>
 * </ul>
 *
 * <p>The generated controllers carry {@code @Tag} (per resource) and
 * {@code @Operation} (per endpoint) annotations that springdoc reads at startup.
 * Adjust this class to add security schemes, multiple servers, or extended info
 * — see <a href="https://springdoc.org/">springdoc.org</a>.</p>
 */
@Configuration
@OpenAPIDefinition(
        info = @Info(
                title = "${projectName} API",
                version = "0.0.1",
                description = "Generated by Umaboot"
        ),
        servers = {
                @Server(url = "http://localhost:8080", description = "Local development")
        }
)
public class OpenApiConfig {
}
