// Generated by Umaboot. Run `gradle wrapper` once to materialize the wrapper JAR + scripts.
plugins {
    java
<#if springBoot2>
    id("org.springframework.boot") version "${springBootVersion}"
    id("io.spring.dependency-management") version "1.0.15.RELEASE"
<#else>
    id("org.springframework.boot") version "${springBootVersion}"
    id("io.spring.dependency-management") version "1.1.6"
</#if>
<#if isJooq>
    id("nu.studer.jooq") version "${jooqGradlePluginVersion}"
</#if>
}

group = "${projectGroup}"
version = "0.0.1-SNAPSHOT"

<#if isJooq>
extra["jooq.version"] = "${jooqVersion}"

</#if>
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(${javaVersion})
    }
}

repositories {
    mavenCentral()
}

<#if isMyBatis>
val mybatisStarterVersion = "<#if springBoot2>2.3.2<#else>3.0.4</#if>"
</#if>
<#if useMapStruct>
val mapstructVersion = "1.6.3"
val lombokMapstructBindingVersion = "0.2.0"
</#if>
<#if testsEnabled && !dbIsSqlite>
val testcontainersVersion = "1.20.4"
</#if>

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-validation")
<#if migrationFlyway>
    implementation("org.flywaydb:flyway-core")
<#if renderFlywayDatabaseModule>
    runtimeOnly("org.flywaydb:${flywayDatabaseModule}")
</#if>
</#if>
<#if loggingJson>
    implementation("net.logstash.logback:logstash-logback-encoder:${logstashLogbackEncoderVersion}")
</#if>
<#if securityEnabled>
    implementation("org.springframework.boot:spring-boot-starter-security")
</#if>
<#if securityJwt>
    implementation("io.jsonwebtoken:jjwt-api:0.11.5")
    runtimeOnly("io.jsonwebtoken:jjwt-impl:0.11.5")
    runtimeOnly("io.jsonwebtoken:jjwt-jackson:0.11.5")
</#if>
<#if openApiAnnotation>
    implementation("org.springdoc:${springdocOpenApiArtifactId}:${springdocOpenApiVersion}")
</#if>
<#if isJpa>
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
<#else>
    // PageResponse.java imports org.springframework.data.domain.Page so its static
    // of(Page<T>) factory works. JPA pulls spring-data-commons in transitively;
    // for MyBatis / jOOQ projects we declare it explicitly.
    implementation("org.springframework.data:spring-data-commons")
</#if>
<#if isMyBatis>
    implementation("org.mybatis.spring.boot:mybatis-spring-boot-starter:${r"$"}mybatisStarterVersion")
</#if>
<#if isJooq>
    implementation("org.springframework.boot:spring-boot-starter-jooq")
</#if>
<#if dbIsMariadb>
    runtimeOnly("org.mariadb.jdbc:mariadb-java-client")
<#elseif dbIsMysql>
    runtimeOnly("com.mysql:mysql-connector-j")
<#elseif dbIsSqlserver>
    runtimeOnly("com.microsoft.sqlserver:mssql-jdbc")
<#elseif dbIsSqlite>
    runtimeOnly("org.xerial:sqlite-jdbc")
<#else>
    runtimeOnly("org.postgresql:postgresql")
</#if>
<#if dbIsSqlite && isJpa>
    // SQLite has no Hibernate dialect in core; the community-maintained
    // SQLiteDialect lives in hibernate-community-dialects.
    implementation("org.hibernate.orm:hibernate-community-dialects")
</#if>
<#if useLombok>
    compileOnly("org.projectlombok:lombok<#if lombokVersion?? && lombokVersion?has_content>:${lombokVersion}</#if>")
    annotationProcessor("org.projectlombok:lombok<#if lombokVersion?? && lombokVersion?has_content>:${lombokVersion}</#if>")
</#if>
<#if useMapStruct>
    implementation("org.mapstruct:mapstruct:${r"$"}mapstructVersion")
    annotationProcessor("org.mapstruct:mapstruct-processor:${r"$"}mapstructVersion")
<#if useLombok>
    annotationProcessor("org.projectlombok:lombok-mapstruct-binding:${r"$"}lombokMapstructBindingVersion")
</#if>
</#if>
    testImplementation("org.springframework.boot:spring-boot-starter-test")
<#if testsEnabled && !dbIsSqlite>
    testImplementation(platform("org.testcontainers:testcontainers-bom:${r"$"}testcontainersVersion"))
    testImplementation("org.testcontainers:junit-jupiter")
    testImplementation("org.testcontainers:<#if dbIsMariadb>mariadb<#elseif dbIsMysql>mysql<#elseif dbIsSqlserver>mssqlserver<#else>postgresql</#if>")
</#if>
<#if isJooq>
    // jOOQ codegen plugin needs the JDBC driver on its classpath.
    jooqGenerator("${jooqCodegenDriverCoordinate}")
</#if>
}

tasks.withType<Test> {
    useJUnitPlatform()
}

<#if isJooq>
// jOOQ codegen reads the schema from the live DB at build time and produces
// ${basePackage}.jooq.* classes under build/generated/jooq/main.
jooq {
    version.set("${jooqVersion}")
    edition.set(nu.studer.gradle.jooq.JooqEdition.OSS)
    configurations {
        create("main") {
            generateSchemaSourceOnCompilation.set(true)
            jooqConfiguration.apply {
                jdbc.apply {
                    driver = "${jdbcDriverClass}"
                    url = "${jdbcUrl}"
                    user = "${jdbcUsername}"
                    password = "${jdbcPassword}"
                }
                generator.apply {
                    name = "org.jooq.codegen.JavaGenerator"
                    database.apply {
                        name = "<#if dbIsMariadb>org.jooq.meta.mariadb.MariaDBDatabase<#elseif dbIsMysql>org.jooq.meta.mysql.MySQLDatabase<#elseif dbIsSqlserver>org.jooq.meta.sqlserver.SQLServerDatabase<#elseif dbIsSqlite>org.jooq.meta.sqlite.SQLiteDatabase<#else>org.jooq.meta.postgres.PostgresDatabase</#if>"
                        inputSchema = "${schemaName}"
                    }
                    generate.apply {
                        isPojos = true
                        isDaos = false
                        isRecords = true
                    }
                    target.apply {
                        packageName = "${basePackage}.jooq"
                        directory = "build/generated/jooq/main"
                    }
                }
            }
        }
    }
}
</#if>
