<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>${springBootVersion}</version>
        <relativePath/>
    </parent>

    <groupId>${projectGroup}</groupId>
    <artifactId>${projectName}</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>${projectName}</name>
    <description>Hexagonal Spring Boot project generated by Umaboot</description>

    <properties>
        <java.version>${javaVersion}</java.version>
<#if isMyBatis>
        <mybatis.starter.version><#if springBoot2>2.3.2<#else>3.0.4</#if></mybatis.starter.version>
</#if>
<#if isJooq>
        <jooq.version>${jooqVersion}</jooq.version>
</#if>
<#if testsEnabled && !dbIsSqlite>
        <testcontainers.version>1.20.4</testcontainers.version>
</#if>
    </properties>

<#if testsEnabled && !dbIsSqlite>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-bom</artifactId>
                <version>${r"${testcontainers.version}"}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</#if>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
<#if loggingJson>
        <dependency>
            <groupId>net.logstash.logback</groupId>
            <artifactId>logstash-logback-encoder</artifactId>
            <version>7.4</version>
        </dependency>
</#if>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
<#if migrationFlyway>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>
<#if renderFlywayDatabaseModule>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>${flywayDatabaseModule}</artifactId>
            <scope>runtime</scope>
        </dependency>
</#if>
</#if>
<#if securityEnabled>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
</#if>
<#if securityJwt>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
            <version>0.11.5</version>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-impl</artifactId>
            <version>0.11.5</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId>
            <version>0.11.5</version>
            <scope>runtime</scope>
        </dependency>
</#if>
<#if openApiAnnotation>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>${springdocOpenApiArtifactId}</artifactId>
            <version>${springdocOpenApiVersion}</version>
        </dependency>
</#if>
<#if isJpa>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
<#else>
        <!--
          PageResponse.java imports org.springframework.data.domain.Page so its
          static of(Page<T>) factory works. JPA pulls spring-data-commons in
          transitively; for MyBatis / jOOQ projects we declare it explicitly so
          the generated PageResponse.java compiles.
        -->
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-commons</artifactId>
        </dependency>
</#if>
<#if isMyBatis>
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>${r"${mybatis.starter.version}"}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
</#if>
<#if isJooq>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jooq</artifactId>
        </dependency>
</#if>
        <dependency>
<#if dbIsMariadb>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
<#elseif dbIsMysql>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
<#elseif dbIsSqlserver>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
<#elseif dbIsSqlite>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
<#else>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
</#if>
            <scope>runtime</scope>
        </dependency>
<#if dbIsSqlite && isJpa>
        <!--
          SQLite has no Hibernate dialect in core. The community-maintained
          SQLiteDialect lives in `org.hibernate.orm:hibernate-community-dialects`
          (managed by spring-boot-starter-parent for SB3, by spring-boot-dependencies
          for SB2). Wire it in via `spring.jpa.properties.hibernate.dialect:
          org.hibernate.community.dialect.SQLiteDialect` in application.yml.
        -->
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-community-dialects</artifactId>
        </dependency>
</#if>
<#if useLombok>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
</#if>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
<#if testsEnabled && !dbIsSqlite>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId><#if dbIsMariadb>mariadb<#elseif dbIsMysql>mysql<#elseif dbIsSqlserver>mssqlserver<#else>postgresql</#if></artifactId>
            <scope>test</scope>
        </dependency>
</#if>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
<#if useLombok>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
</#if>
            </plugin>
<#if isJooq>
            <!--
              jOOQ codegen runs at `mvn compile` and produces ${basePackage}.jooq.* classes.
              The Hex outbound adapter uses Tables.{TABLE} static refs from this package.
            -->
            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>${r"${jooq.version}"}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>${jooqCodegenDriverGroupId}</groupId>
                        <artifactId>${jooqCodegenDriverArtifactId}</artifactId>
                        <version>${jooqCodegenDriverVersion}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <jdbc>
                        <driver>${jdbcDriverClass}</driver>
                        <url>${jdbcUrl}</url>
                        <user>${jdbcUsername}</user>
                        <password>${jdbcPassword}</password>
                    </jdbc>
                    <generator>
                        <database>
                            <name><#if dbIsMariadb>org.jooq.meta.mariadb.MariaDBDatabase<#elseif dbIsMysql>org.jooq.meta.mysql.MySQLDatabase<#elseif dbIsSqlserver>org.jooq.meta.sqlserver.SQLServerDatabase<#elseif dbIsSqlite>org.jooq.meta.sqlite.SQLiteDatabase<#else>org.jooq.meta.postgres.PostgresDatabase</#if></name>
                            <inputSchema>${schemaName}</inputSchema>
                        </database>
                        <generate>
                            <pojos>true</pojos>
                            <daos>false</daos>
                            <records>true</records>
                        </generate>
                        <target>
                            <packageName>${basePackage}.jooq</packageName>
                            <directory>target/generated-sources/jooq</directory>
                        </target>
                    </generator>
                </configuration>
            </plugin>
</#if>
        </plugins>
    </build>
</project>
