package io.umaboot.core.generator;

import io.umaboot.core.GenerationPipeline;
import io.umaboot.core.config.UmabootConfig;
import io.umaboot.core.generator.migration.FlywayMigrationRenderer;
import io.umaboot.core.generator.mvc.MvcGenerator;
import io.umaboot.core.model.ColumnModel;
import io.umaboot.core.model.RelationshipModel;
import io.umaboot.core.model.RelationshipType;
import io.umaboot.core.model.SchemaModel;
import io.umaboot.core.model.TableModel;
import io.umaboot.core.template.TemplateEngine;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Types;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class FlywayMigrationRenderTest {

    @Test
    void schemaFileMode_copiesSchemaSqlIntoFlywayMigration(@TempDir Path tmp) throws Exception {
        Path schemaFile = tmp.resolve("schema.sql");
        Files.writeString(schemaFile, """
                CREATE TABLE users (
                  id BIGINT AUTO_INCREMENT PRIMARY KEY,
                  username VARCHAR(100) NOT NULL
                );
                """);

        var generation = generation("gradle", "mysql", schemaFile.toString(), "mysql");
        GenerationPipeline.Result result = GenerationPipeline.run(new UmabootConfig(null, generation), null);

        String migration = readUnit(result.units(), FlywayMigrationRenderer.PATH);
        assertThat(migration)
                .contains("Copied from generation.schemaFile")
                .contains("CREATE TABLE users")
                .contains("AUTO_INCREMENT PRIMARY KEY");

        String gradle = readUnit(result.units(), "build.gradle.kts");
        assertThat(gradle)
                .contains("implementation(\"org.flywaydb:flyway-core\")")
                .contains("runtimeOnly(\"org.flywaydb:flyway-mysql\")");

        String sqliteTestOverride = readUnit(result.units(),
                "src/test/java/com/example/app/AbstractIntegrationTest.java");
        assertThat(sqliteTestOverride).doesNotContain("create-drop");
    }

    @Test
    void liveDbMode_rendersInitialMigrationFromSchemaModel() {
        List<GeneratedUnit> units = new MvcGenerator(new TemplateEngine(null),
                ctx("maven", "postgresql", null))
                .generate(liveSchema());

        String migration = readUnit(units, FlywayMigrationRenderer.PATH);
        assertThat(migration)
                .contains("Generated from live database introspection")
                .contains("CREATE SCHEMA IF NOT EXISTS \"public\"")
                .contains("CREATE TABLE \"public\".\"customers\"")
                .contains("\"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL")
                .contains("PRIMARY KEY (\"id\")")
                .contains("CREATE TABLE \"public\".\"orders\"")
                .contains("ALTER TABLE \"public\".\"orders\" ADD CONSTRAINT")
                .contains("FOREIGN KEY (\"customer_id\") REFERENCES \"public\".\"customers\" (\"id\")");

        String pom = readUnit(units, "pom.xml");
        assertThat(pom)
                .contains("<artifactId>flyway-core</artifactId>")
                .contains("<artifactId>flyway-database-postgresql</artifactId>")
                .doesNotContain("<artifactId>flyway-mysql</artifactId>");
    }

    @Test
    void springBoot2MysqlGradle_includesBootManagedFlywayMysqlModule() {
        List<GeneratedUnit> units = new MvcGenerator(new TemplateEngine(null),
                ctx("gradle", "mysql", null, "2.7.18", "1.8"))
                .generate(liveSchema());

        String gradle = readUnit(units, "build.gradle.kts");
        assertThat(gradle)
                .contains("implementation(\"org.flywaydb:flyway-core\")")
                .contains("runtimeOnly(\"org.flywaydb:flyway-mysql\")")
                .doesNotContain("flyway-database-postgresql")
                .doesNotContain("flyway-sqlserver");
    }

    @Test
    void springBoot2Maven_rendersOnlyDatabaseModulesCompatibleWithFlyway8() {
        assertSpringBoot2MavenFlywayModule("mysql", "flyway-mysql");
        assertSpringBoot2MavenFlywayModule("mariadb", "flyway-mysql");
        assertSpringBoot2MavenFlywayModule("sqlserver", "flyway-sqlserver");
        assertSpringBoot2MavenFlywayModule("postgresql", null);
        assertSpringBoot2MavenFlywayModule("sqlite", null);
    }

    @Test
    void migrationNone_skipsFlywayFileAndDependencies() {
        List<GeneratedUnit> units = new MvcGenerator(new TemplateEngine(null),
                ctx("gradle", "mysql", UmabootConfig.MigrationOptions.defaults()))
                .generate(liveSchema());

        assertThat(units).extracting(GeneratedUnit::relativePath)
                .doesNotContain(FlywayMigrationRenderer.PATH);
        assertThat(readUnit(units, "build.gradle.kts")).doesNotContain("org.flywaydb");
    }

    @Test
    void migrationNone_jpaTestcontainersUseSchemaSqlAndHibernateValidate() {
        List<GeneratedUnit> units = new MvcGenerator(new TemplateEngine(null),
                ctx("maven", "postgresql", UmabootConfig.MigrationOptions.defaults()))
                .generate(liveSchema());

        assertThat(units).extracting(GeneratedUnit::relativePath)
                .contains("src/test/resources/schema.sql")
                .doesNotContain(FlywayMigrationRenderer.PATH);

        String baseTest = readUnit(units, "src/test/java/com/example/app/AbstractIntegrationTest.java");
        assertThat(baseTest)
                .contains(".withInitScript(\"schema.sql\")")
                .contains("registerSchemaMode(registry);")
                .contains("registry.add(\"spring.jpa.hibernate.ddl-auto\", () -> \"validate\");")
                .doesNotContain("create-drop")
                .doesNotContain("spring.sql.init.mode");

        String schemaSql = readUnit(units, "src/test/resources/schema.sql");
        assertThat(schemaSql)
                .contains("Generated by Umaboot for integration tests")
                .contains("CREATE TABLE \"public\".\"customers\"");
    }

    @Test
    void migrationFlyway_testcontainerTestsUseHibernateValidate() {
        List<GeneratedUnit> units = new MvcGenerator(new TemplateEngine(null),
                ctx("maven", "postgresql", new UmabootConfig.MigrationOptions("flyway")))
                .generate(liveSchema());

        assertThat(units).extracting(GeneratedUnit::relativePath)
                .contains(FlywayMigrationRenderer.PATH)
                .doesNotContain("src/test/resources/schema.sql");

        String baseTest = readUnit(units, "src/test/java/com/example/app/AbstractIntegrationTest.java");
        assertThat(baseTest)
                .contains("registerSchemaMode(registry);")
                .contains("registry.add(\"spring.jpa.hibernate.ddl-auto\", () -> \"validate\");")
                .doesNotContain("create-drop")
                .doesNotContain(".withInitScript(\"schema.sql\")");
    }

    @Test
    void migrationNone_nonJpaTestcontainersUseSchemaSqlInitScript() {
        List<GeneratedUnit> units = new MvcGenerator(new TemplateEngine(null),
                ctx("maven", "postgresql", UmabootConfig.MigrationOptions.defaults(),
                        "3.3.5", "17", "mybatis"))
                .generate(liveSchema());

        assertThat(units).extracting(GeneratedUnit::relativePath)
                .contains("src/test/resources/schema.sql")
                .doesNotContain(FlywayMigrationRenderer.PATH);

        String baseTest = readUnit(units, "src/test/java/com/example/app/AbstractIntegrationTest.java");
        assertThat(baseTest)
                .contains(".withInitScript(\"schema.sql\")")
                .doesNotContain("spring.sql.init.mode")
                .doesNotContain("spring.jpa.hibernate.ddl-auto");

        String schemaSql = readUnit(units, "src/test/resources/schema.sql");
        assertThat(schemaSql)
                .contains("Generated by Umaboot for integration tests")
                .contains("CREATE TABLE \"public\".\"customers\"");
    }

    @Test
    void migrationNone_allArchitecturesEmitTestSchema() {
        for (String architecture : List.of("mvc", "hexagonal", "ddd")) {
            GeneratorContext ctx = ctx("maven", "postgresql", UmabootConfig.MigrationOptions.defaults(),
                    "3.3.5", "17", "jpa", architecture);
            List<GeneratedUnit> units = ArchitectureGenerators.forContext(ctx, new TemplateEngine(null))
                    .generate(liveSchema());

            assertThat(units).extracting(GeneratedUnit::relativePath)
                    .contains("src/test/resources/schema.sql")
                    .doesNotContain(FlywayMigrationRenderer.PATH);
        }
    }

    @Test
    void migrationFlyway_nonJpaTestsUseFlywayMigrationOnly() {
        List<GeneratedUnit> units = new MvcGenerator(new TemplateEngine(null),
                ctx("maven", "postgresql", new UmabootConfig.MigrationOptions("flyway"),
                        "3.3.5", "17", "mybatis"))
                .generate(liveSchema());

        assertThat(units).extracting(GeneratedUnit::relativePath)
                .contains(FlywayMigrationRenderer.PATH)
                .doesNotContain("src/test/resources/schema.sql");

        String baseTest = readUnit(units, "src/test/java/com/example/app/AbstractIntegrationTest.java");
        assertThat(baseTest)
                .doesNotContain("spring.sql.init.mode")
                .doesNotContain("spring.jpa.hibernate.ddl-auto");
    }

    private static UmabootConfig.Generation generation(String buildTool, String dbDriver,
                                                       String schemaFile, String schemaDialect) {
        return new UmabootConfig.Generation(
                "mvc",
                "jpa",
                "com.example.app",
                "app",
                "com.example",
                "3.3.5",
                "17",
                true,
                UmabootConfig.OpenApiOptions.defaults(),
                UmabootConfig.InjectionOptions.defaults(),
                UmabootConfig.ValidationOptions.defaults(),
                UmabootConfig.DtoOptions.defaults(),
                UmabootConfig.ExceptionOptions.defaults(),
                UmabootConfig.AuditOptions.defaults(),
                UmabootConfig.SoftDeleteOptions.defaults(),
                UmabootConfig.DockerOptions.defaults(),
                UmabootConfig.CiOptions.defaults(),
                UmabootConfig.LoggingOptions.defaults(),
                new UmabootConfig.TestOptions(true),
                new UmabootConfig.MigrationOptions("flyway"),
                UmabootConfig.PaginationOptions.defaults(),
                UmabootConfig.SecurityOptions.defaults(),
                "./generated",
                new UmabootConfig.JpaOptions(false),
                new UmabootConfig.MyBatisOptions("xml"),
                UmabootConfig.TableFilterOptions.allowAll(),
                UmabootConfig.DddOptions.defaults(),
                UmabootConfig.OutputOptions.defaults(),
                UmabootConfig.ApplicationConfigOptions.defaults(),
                schemaFile,
                schemaDialect,
                buildTool);
    }

    private static GeneratorContext ctx(String buildTool, String dbDriver,
                                        UmabootConfig.MigrationOptions migrations) {
        return ctx(buildTool, dbDriver, migrations, "3.3.5", "17");
    }

    private static GeneratorContext ctx(String buildTool, String dbDriver,
                                        UmabootConfig.MigrationOptions migrations,
                                        String springBootVersion, String javaVersion) {
        return ctx(buildTool, dbDriver, migrations, springBootVersion, javaVersion, "jpa");
    }

    private static GeneratorContext ctx(String buildTool, String dbDriver,
                                        UmabootConfig.MigrationOptions migrations,
                                        String springBootVersion, String javaVersion,
                                        String persistence) {
        return ctx(buildTool, dbDriver, migrations, springBootVersion, javaVersion, persistence, "mvc");
    }

    private static GeneratorContext ctx(String buildTool, String dbDriver,
                                        UmabootConfig.MigrationOptions migrations,
                                        String springBootVersion, String javaVersion,
                                        String persistence, String architecture) {
        return new GeneratorContext(
                "com.example.app",
                "app",
                "com.example",
                springBootVersion,
                javaVersion,
                true,
                architecture,
                persistence,
                "xml",
                false,
                "none",
                "constructor",
                "jakarta",
                "class",
                "separate",
                "problemdetail",
                UmabootConfig.AuditOptions.defaults(),
                UmabootConfig.SoftDeleteOptions.defaults(),
                UmabootConfig.DockerOptions.defaults(),
                UmabootConfig.CiOptions.defaults(),
                UmabootConfig.LoggingOptions.defaults(),
                new UmabootConfig.TestOptions(true),
                migrations == null ? new UmabootConfig.MigrationOptions("flyway") : migrations,
                "offset",
                UmabootConfig.SecurityOptions.defaults(),
                UmabootConfig.DddOptions.defaults(),
                false,
                dbDriver,
                null,
                null,
                UmabootConfig.ApplicationConfigOptions.defaults(),
                "",
                null,
                buildTool);
    }

    private static void assertSpringBoot2MavenFlywayModule(String dbDriver, String expectedModule) {
        List<GeneratedUnit> units = new MvcGenerator(new TemplateEngine(null),
                ctx("maven", dbDriver, null, "2.7.18", "1.8"))
                .generate(liveSchema());

        String pom = readUnit(units, "pom.xml");
        assertThat(pom).contains("<artifactId>flyway-core</artifactId>");
        if (expectedModule == null) {
            assertThat(pom)
                    .doesNotContain("<artifactId>flyway-mysql</artifactId>")
                    .doesNotContain("<artifactId>flyway-sqlserver</artifactId>")
                    .doesNotContain("<artifactId>flyway-database-postgresql</artifactId>");
        } else {
            assertThat(pom).contains("<artifactId>" + expectedModule + "</artifactId>");
        }
    }

    private static SchemaModel liveSchema() {
        ColumnModel customerId = new ColumnModel("id", Types.BIGINT, "bigint", 19, 0,
                false, true, true, null, "", List.of());
        ColumnModel customerName = new ColumnModel("name", Types.VARCHAR, "varchar", 100, 0,
                false, false, false, null, "", List.of());
        TableModel customers = new TableModel("customers", "public", "",
                List.of(customerId, customerName), List.of("id"), List.of(), List.of(), false);

        ColumnModel orderId = new ColumnModel("id", Types.BIGINT, "bigint", 19, 0,
                false, true, true, null, "", List.of());
        ColumnModel customerFk = new ColumnModel("customer_id", Types.BIGINT, "bigint", 19, 0,
                false, false, false, null, "", List.of());
        RelationshipModel fk = new RelationshipModel(
                "orders",
                "customers",
                new RelationshipType.ManyToOne(),
                List.of("customer_id"),
                List.of("id"),
                "customer",
                true,
                false);
        TableModel orders = new TableModel("orders", "public", "",
                List.of(orderId, customerFk), List.of("id"), List.of(), List.of(fk), false);
        return new SchemaModel("public", List.of(customers, orders));
    }

    private static String readUnit(List<GeneratedUnit> units, String path) {
        return units.stream()
                .filter(u -> u.relativePath().equals(path))
                .findFirst()
                .map(GeneratedUnit::content)
                .orElseThrow(() -> new AssertionError("Missing: " + path));
    }
}
