package io.umaboot.core.generator.migration;

import io.umaboot.core.generator.GeneratorContext;
import io.umaboot.core.model.ColumnModel;
import io.umaboot.core.model.RelationshipModel;
import io.umaboot.core.model.SchemaModel;
import io.umaboot.core.model.TableModel;

import java.sql.Types;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Renders the initial Flyway SQL migration for generated projects.
 *
 * <p>Schema-file mode is exact-copy so DB-specific DDL is preserved. Live-DB
 * mode is a pragmatic model-to-DDL renderer: tables, columns, primary keys,
 * unique constraints, and owning foreign keys.</p>
 */
public final class FlywayMigrationRenderer {

    public static final String PATH = "src/main/resources/db/migration/V1__init_schema.sql";

    private FlywayMigrationRenderer() {}

    public static String render(SchemaModel schema, GeneratorContext ctx) {
        return render(schema, ctx, "Generated by Umaboot for Flyway");
    }

    public static String renderTestSchema(SchemaModel schema, GeneratorContext ctx) {
        return render(schema, ctx, "Generated by Umaboot for integration tests");
    }

    private static String render(SchemaModel schema, GeneratorContext ctx, String headerTitle) {
        String sourceSql = ctx.schemaFileSql();
        if (sourceSql != null && !sourceSql.isBlank()) {
            return header(headerTitle, "Copied from generation.schemaFile")
                    + ensureSqlTerminated(sourceSql.trim()) + "\n";
        }

        StringBuilder out = new StringBuilder();
        out.append(header(headerTitle, "Generated from live database introspection"));
        appendSchemaPrelude(out, schema, ctx);
        appendEnumTypes(out, schema, ctx);
        for (TableModel table : schema.tables()) {
            appendCreateTable(out, table, ctx);
        }
        appendForeignKeys(out, schema, ctx);
        return out.toString();
    }

    private static String header(String title, String mode) {
        return "-- " + title + ".\n"
                + "-- " + mode + ". Review before using in production.\n\n";
    }

    private static void appendSchemaPrelude(StringBuilder out, SchemaModel schema, GeneratorContext ctx) {
        if (ctx.isDbPostgres()) {
            out.append("CREATE SCHEMA IF NOT EXISTS ")
                    .append(q(schema.schemaName(), ctx))
                    .append(";\n\n");
        } else if (ctx.isDbSqlserver()) {
            out.append("IF SCHEMA_ID(N'")
                    .append(escapeSqlString(schema.schemaName()))
                    .append("') IS NULL EXEC(N'CREATE SCHEMA ")
                    .append(q(schema.schemaName(), ctx).replace("'", "''"))
                    .append("');\n\n");
        }
    }

    private static void appendEnumTypes(StringBuilder out, SchemaModel schema, GeneratorContext ctx) {
        if (!ctx.isDbPostgres()) return;
        Map<String, List<String>> enumTypes = new LinkedHashMap<>();
        for (TableModel table : schema.tables()) {
            for (ColumnModel column : table.columns()) {
                if (column.isEnum() && !column.sqlType().isBlank()) {
                    enumTypes.putIfAbsent(column.sqlType(), column.enumValues());
                }
            }
        }
        for (var entry : enumTypes.entrySet()) {
            out.append("CREATE TYPE ")
                    .append(qualifiedName(schema.schemaName(), entry.getKey(), ctx))
                    .append(" AS ENUM (")
                    .append(entry.getValue().stream()
                            .map(v -> "'" + escapeSqlString(v) + "'")
                            .reduce((a, b) -> a + ", " + b)
                            .orElse(""))
                    .append(");\n");
        }
        if (!enumTypes.isEmpty()) out.append("\n");
    }

    private static void appendCreateTable(StringBuilder out, TableModel table, GeneratorContext ctx) {
        out.append("CREATE TABLE ")
                .append(qualifiedName(table.schema(), table.name(), ctx))
                .append(" (\n");

        List<String> lines = new ArrayList<>();
        boolean inlineSqlitePk = false;
        for (ColumnModel column : table.columns()) {
            boolean inlinePk = ctx.isDbSqlite()
                    && column.autoIncrement()
                    && column.primaryKey()
                    && table.primaryKey().size() == 1;
            if (inlinePk) inlineSqlitePk = true;
            lines.add("    " + columnDefinition(column, table, ctx, inlinePk));
        }

        if (!table.primaryKey().isEmpty() && !inlineSqlitePk) {
            lines.add("    CONSTRAINT " + q(constraintName("pk", table.name(), table.primaryKey()), ctx)
                    + " PRIMARY KEY (" + columnList(table.primaryKey(), ctx) + ")");
        }

        int uniqueIndex = 1;
        for (List<String> unique : table.uniqueConstraints()) {
            if (unique == null || unique.isEmpty()) continue;
            lines.add("    CONSTRAINT " + q(constraintName("uq" + uniqueIndex++, table.name(), unique), ctx)
                    + " UNIQUE (" + columnList(unique, ctx) + ")");
        }

        out.append(String.join(",\n", lines));
        out.append("\n);\n\n");
    }

    private static String columnDefinition(ColumnModel column, TableModel table,
                                           GeneratorContext ctx, boolean inlineSqlitePk) {
        StringBuilder b = new StringBuilder();
        b.append(q(column.name(), ctx)).append(' ');
        b.append(columnSqlType(column, ctx, inlineSqlitePk));

        if (inlineSqlitePk) {
            b.append(" PRIMARY KEY AUTOINCREMENT");
            return b.toString();
        }

        if (column.autoIncrement()) {
            if (ctx.isDbMysqlFamily()) {
                b.append(" AUTO_INCREMENT");
            } else if (ctx.isDbSqlserver()) {
                b.append(" IDENTITY(1,1)");
            } else if (ctx.isDbPostgres()) {
                b.append(" GENERATED BY DEFAULT AS IDENTITY");
            }
        }

        if (!column.nullable() || column.primaryKey()) {
            b.append(" NOT NULL");
        }
        if (!column.autoIncrement() && column.defaultValue() != null && !column.defaultValue().isBlank()) {
            b.append(" DEFAULT ").append(column.defaultValue());
        }
        return b.toString();
    }

    private static String columnSqlType(ColumnModel column, GeneratorContext ctx, boolean inlineSqlitePk) {
        if (inlineSqlitePk) return "INTEGER";
        if (column.isEnum()) {
            if (ctx.isDbPostgres() && !column.sqlType().isBlank()) {
                return q(column.sqlType(), ctx);
            }
            if (ctx.isDbMysqlFamily()) {
                return "ENUM (" + column.enumValues().stream()
                        .map(v -> "'" + escapeSqlString(v) + "'")
                        .reduce((a, b) -> a + ", " + b)
                        .orElse("'UNKNOWN'") + ")";
            }
        }

        String sqlType = column.sqlType() == null ? "" : column.sqlType().trim();
        if (sqlType.isBlank()) {
            sqlType = fallbackSqlType(column.jdbcType(), ctx);
        }
        if (sqlType.contains("(")) {
            return sqlType;
        }
        String lower = sqlType.toLowerCase(Locale.ROOT);
        if (column.size() > 0 && switch (lower) {
            case "char", "character", "varchar", "character varying",
                    "nchar", "nvarchar", "binary", "varbinary" -> true;
            default -> false;
        }) {
            return sqlType + "(" + column.size() + ")";
        }
        if (column.size() > 0 && switch (lower) {
            case "decimal", "numeric", "number" -> true;
            default -> false;
        }) {
            return sqlType + "(" + column.size() + (column.scale() > 0 ? "," + column.scale() : "") + ")";
        }
        return sqlType;
    }

    private static String fallbackSqlType(int jdbcType, GeneratorContext ctx) {
        return switch (jdbcType) {
            case Types.BIGINT -> ctx.isDbSqlite() ? "INTEGER" : "BIGINT";
            case Types.INTEGER -> ctx.isDbSqlite() ? "INTEGER" : "INT";
            case Types.SMALLINT -> "SMALLINT";
            case Types.TINYINT -> ctx.isDbPostgres() ? "SMALLINT" : "TINYINT";
            case Types.BOOLEAN, Types.BIT -> ctx.isDbMysqlFamily() ? "BOOLEAN" : "BOOLEAN";
            case Types.DECIMAL, Types.NUMERIC -> "DECIMAL";
            case Types.DOUBLE, Types.FLOAT, Types.REAL -> "DOUBLE";
            case Types.DATE -> "DATE";
            case Types.TIMESTAMP, Types.TIMESTAMP_WITH_TIMEZONE -> "TIMESTAMP";
            case Types.TIME, Types.TIME_WITH_TIMEZONE -> "TIME";
            case Types.BINARY, Types.VARBINARY, Types.LONGVARBINARY -> ctx.isDbPostgres() ? "BYTEA" : "BLOB";
            default -> "VARCHAR(255)";
        };
    }

    private static void appendForeignKeys(StringBuilder out, SchemaModel schema, GeneratorContext ctx) {
        boolean wroteAny = false;
        for (TableModel table : schema.tables()) {
            for (RelationshipModel rel : table.relationships()) {
                if (!rel.owning() || rel.fromColumns().isEmpty() || rel.toColumns().isEmpty()) {
                    continue;
                }
                out.append("ALTER TABLE ")
                        .append(qualifiedName(table.schema(), rel.fromTable(), ctx))
                        .append(" ADD CONSTRAINT ")
                        .append(q(constraintName("fk", rel.fromTable() + "_" + rel.toTable(), rel.fromColumns()), ctx))
                        .append(" FOREIGN KEY (")
                        .append(columnList(rel.fromColumns(), ctx))
                        .append(") REFERENCES ")
                        .append(qualifiedName(table.schema(), rel.toTable(), ctx))
                        .append(" (")
                        .append(columnList(rel.toColumns(), ctx))
                        .append(");\n");
                wroteAny = true;
            }
        }
        if (wroteAny) out.append("\n");
    }

    private static String columnList(List<String> columns, GeneratorContext ctx) {
        return columns.stream().map(c -> q(c, ctx)).reduce((a, b) -> a + ", " + b).orElse("");
    }

    private static String qualifiedName(String schema, String name, GeneratorContext ctx) {
        if ((ctx.isDbPostgres() || ctx.isDbSqlserver()) && schema != null && !schema.isBlank()) {
            return q(schema, ctx) + "." + q(name, ctx);
        }
        return q(name, ctx);
    }

    private static String q(String identifier, GeneratorContext ctx) {
        String id = identifier == null ? "" : identifier;
        if (ctx.isDbMysqlFamily()) return "`" + id.replace("`", "``") + "`";
        if (ctx.isDbSqlserver()) return "[" + id.replace("]", "]]") + "]";
        return "\"" + id.replace("\"", "\"\"") + "\"";
    }

    private static String constraintName(String prefix, String table, List<String> columns) {
        String raw = prefix + "_" + table + "_" + String.join("_", columns);
        String sanitized = raw.replaceAll("[^A-Za-z0-9_]", "_").toLowerCase(Locale.ROOT);
        if (sanitized.length() <= 60) return sanitized;
        return sanitized.substring(0, 50) + "_" + Integer.toHexString(sanitized.hashCode());
    }

    private static String escapeSqlString(String value) {
        return value == null ? "" : value.replace("'", "''");
    }

    private static String ensureSqlTerminated(String sql) {
        return sql.endsWith(";") ? sql : sql + ";";
    }
}
