package io.umaboot.core.standalone;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.stream.Stream;

/**
 * Safety checks for standalone generation into an existing directory.
 */
public final class StandaloneOutputSafety {

    public static final String MARKER_FILE = ".umaboot-standalone";

    private StandaloneOutputSafety() {}

    public static Plan inspect(Path outputDir, String existingPolicy) {
        Objects.requireNonNull(outputDir, "outputDir");
        String policy = existingPolicy == null || existingPolicy.isBlank()
                ? "warn"
                : existingPolicy.toLowerCase();
        Path output = outputDir.toAbsolutePath().normalize();

        boolean exists = Files.exists(output);
        boolean marker = exists && Files.exists(output.resolve(MARKER_FILE));
        List<String> markers = exists ? projectMarkers(output) : List.of();
        boolean protectedRoot = markers.contains(".git") || markers.contains("umaboot.yaml");
        boolean existingProject = !markers.isEmpty();
        boolean requiresWarning = existingProject && (!marker || protectedRoot);

        return new Plan(output, policy, exists, existingProject, marker,
                protectedRoot, requiresWarning, markers);
    }

    public static void clean(Plan plan) {
        Objects.requireNonNull(plan, "plan");
        if (!plan.exists()) {
            return;
        }
        if (plan.protectedRoot()) {
            throw new IllegalStateException(
                    "Refusing to clean standalone output because it contains protected project files: "
                            + String.join(", ", plan.markers()));
        }
        Path output = plan.outputDir();
        try (Stream<Path> walk = Files.walk(output)) {
            List<Path> paths = walk
                    .filter(path -> !path.equals(output))
                    .sorted(Comparator.reverseOrder())
                    .toList();
            for (Path path : paths) {
                Files.deleteIfExists(path);
            }
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to clean standalone output: " + output, e);
        }
    }

    public static void writeMarker(Path outputDir) {
        Path output = outputDir.toAbsolutePath().normalize();
        try {
            Files.createDirectories(output);
            Files.writeString(output.resolve(MARKER_FILE),
                    "Generated by Umaboot standalone mode.\n",
                    StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to write " + MARKER_FILE + " in " + output, e);
        }
    }

    private static List<String> projectMarkers(Path output) {
        List<String> markers = new ArrayList<>();
        addIfExists(markers, output, ".git");
        addIfExists(markers, output, "umaboot.yaml");
        addIfExists(markers, output, "pom.xml");
        addIfExists(markers, output, "build.gradle");
        addIfExists(markers, output, "build.gradle.kts");
        addIfExists(markers, output, "settings.gradle");
        addIfExists(markers, output, "settings.gradle.kts");
        addIfExists(markers, output, "Dockerfile");
        addIfExists(markers, output, "docker-compose.yml");
        addIfExists(markers, output, Path.of("src", "main"), "src/main");
        return List.copyOf(markers);
    }

    private static void addIfExists(List<String> markers, Path output, String relativePath) {
        if (Files.exists(output.resolve(relativePath))) {
            markers.add(relativePath.replace('\\', '/'));
        }
    }

    private static void addIfExists(List<String> markers, Path output, Path relativePath, String displayPath) {
        if (Files.exists(output.resolve(relativePath))) {
            markers.add(displayPath);
        }
    }

    public record Plan(
            Path outputDir,
            String existingPolicy,
            boolean exists,
            boolean existingProject,
            boolean umabootMarked,
            boolean protectedRoot,
            boolean requiresWarning,
            List<String> markers) {

        public boolean shouldBlock() {
            return existingProject && ("fail".equals(existingPolicy) || ("warn".equals(existingPolicy) && requiresWarning));
        }

        public boolean shouldClean() {
            return "clean".equals(existingPolicy);
        }

        public boolean shouldOverwrite() {
            return "overwrite".equals(existingPolicy) || ("warn".equals(existingPolicy) && !requiresWarning);
        }

        public String markerSummary() {
            return markers.isEmpty() ? "none" : String.join(", ", markers);
        }
    }
}
