package io.umaboot.core.generator.openapi;

import io.umaboot.core.generator.GeneratorContext;
import io.umaboot.core.generator.JavaTypeMapper;
import io.umaboot.core.model.ColumnModel;
import io.umaboot.core.model.SchemaModel;
import io.umaboot.core.model.TableModel;
import io.umaboot.core.template.Naming;

import java.util.List;
import java.util.Locale;
import java.util.Objects;

/**
 * Emits an OpenAPI 3.0 YAML for the generated REST surface.
 *
 * <p>For each non-junction table:</p>
 * <ul>
 *   <li>{@code POST /api/{plural}}, {@code GET /api/{plural}}, {@code GET /api/{plural}/{id}},
 *       {@code PUT /api/{plural}/{id}}, {@code DELETE /api/{plural}/{id}}</li>
 *   <li>{@code components.schemas.{Entity}RequestDTO} and {@code .{Entity}ResponseDTO}</li>
 * </ul>
 *
 * <p>Hand-built (not via a library) so the core stays dependency-light and the
 * output is stable and human-readable.</p>
 */
public final class OpenApiEmitter {

    private final GeneratorContext ctx;

    public OpenApiEmitter(GeneratorContext ctx) {
        this.ctx = Objects.requireNonNull(ctx, "ctx");
    }

    public String emit(SchemaModel schema) {
        StringBuilder sb = new StringBuilder();
        sb.append("openapi: 3.0.3\n");
        sb.append("info:\n");
        sb.append("  title: ").append(ctx.projectName()).append(" API\n");
        sb.append("  version: 0.0.1\n");
        sb.append("  description: Generated by Umaboot\n");
        sb.append("servers:\n");
        sb.append("  - url: http://localhost:8080\n\n");

        sb.append("paths:\n");
        for (TableModel table : schema.tables()) {
            if (table.junction()) continue;
            String entityName = Naming.entityClass(
                    table.name(),
                    ctx.classNameStripPrefix(),
                    ctx.tableOverride(table.name())
                            .map(io.umaboot.core.config.UmabootConfig.TableOverride::className)
                            .filter(s -> !s.isBlank())
                            .orElse(null));
            String plural = entityName.toLowerCase(Locale.ROOT) + "s";
            emitPaths(sb, entityName, plural);
        }

        sb.append("components:\n");
        sb.append("  schemas:\n");
        for (TableModel table : schema.tables()) {
            if (table.junction()) continue;
            String entityName = Naming.entityClass(
                    table.name(),
                    ctx.classNameStripPrefix(),
                    ctx.tableOverride(table.name())
                            .map(io.umaboot.core.config.UmabootConfig.TableOverride::className)
                            .filter(s -> !s.isBlank())
                            .orElse(null));
            emitSchemas(sb, entityName, table);
        }
        sb.append("    Page:\n");
        sb.append("      type: object\n");
        sb.append("      properties:\n");
        sb.append("        content: { type: array, items: { type: object } }\n");
        sb.append("        totalElements: { type: integer, format: int64 }\n");
        sb.append("        totalPages: { type: integer }\n");
        sb.append("        size: { type: integer }\n");
        sb.append("        number: { type: integer }\n");

        return sb.toString();
    }

    private void emitPaths(StringBuilder sb, String entityName, String plural) {
        String tag = entityName;
        // Collection paths
        sb.append("  /api/").append(plural).append(":\n");
        sb.append("    post:\n");
        sb.append("      tags: [").append(tag).append("]\n");
        sb.append("      summary: Create ").append(entityName).append('\n');
        sb.append("      requestBody:\n");
        sb.append("        required: true\n");
        sb.append("        content:\n");
        sb.append("          application/json:\n");
        sb.append("            schema: { $ref: '#/components/schemas/").append(entityName).append("RequestDTO' }\n");
        sb.append("      responses:\n");
        sb.append("        '201':\n");
        sb.append("          description: Created\n");
        sb.append("          content:\n");
        sb.append("            application/json:\n");
        sb.append("              schema: { $ref: '#/components/schemas/").append(entityName).append("ResponseDTO' }\n");
        sb.append("        '400': { description: Validation error }\n");
        sb.append("    get:\n");
        sb.append("      tags: [").append(tag).append("]\n");
        sb.append("      summary: List ").append(plural).append('\n');
        sb.append("      parameters:\n");
        sb.append("        - { name: page, in: query, schema: { type: integer, default: 0 } }\n");
        sb.append("        - { name: size, in: query, schema: { type: integer, default: 20 } }\n");
        sb.append("      responses:\n");
        sb.append("        '200':\n");
        sb.append("          description: OK\n");
        sb.append("          content:\n");
        sb.append("            application/json:\n");
        sb.append("              schema: { $ref: '#/components/schemas/Page' }\n");

        // Item paths
        sb.append("  /api/").append(plural).append("/{id}:\n");
        sb.append("    get:\n");
        sb.append("      tags: [").append(tag).append("]\n");
        sb.append("      summary: Get ").append(entityName).append(" by id\n");
        sb.append("      parameters:\n");
        sb.append("        - { name: id, in: path, required: true, schema: { type: string } }\n");
        sb.append("      responses:\n");
        sb.append("        '200':\n");
        sb.append("          description: OK\n");
        sb.append("          content:\n");
        sb.append("            application/json:\n");
        sb.append("              schema: { $ref: '#/components/schemas/").append(entityName).append("ResponseDTO' }\n");
        sb.append("        '404': { description: Not found }\n");
        sb.append("    put:\n");
        sb.append("      tags: [").append(tag).append("]\n");
        sb.append("      summary: Update ").append(entityName).append('\n');
        sb.append("      parameters:\n");
        sb.append("        - { name: id, in: path, required: true, schema: { type: string } }\n");
        sb.append("      requestBody:\n");
        sb.append("        required: true\n");
        sb.append("        content:\n");
        sb.append("          application/json:\n");
        sb.append("            schema: { $ref: '#/components/schemas/").append(entityName).append("RequestDTO' }\n");
        sb.append("      responses:\n");
        sb.append("        '200': { description: OK }\n");
        sb.append("        '404': { description: Not found }\n");
        sb.append("    delete:\n");
        sb.append("      tags: [").append(tag).append("]\n");
        sb.append("      summary: Delete ").append(entityName).append('\n');
        sb.append("      parameters:\n");
        sb.append("        - { name: id, in: path, required: true, schema: { type: string } }\n");
        sb.append("      responses:\n");
        sb.append("        '204': { description: No Content }\n");
        sb.append("        '404': { description: Not found }\n");
    }

    private void emitSchemas(StringBuilder sb, String entityName, TableModel table) {
        sb.append("    ").append(entityName).append("RequestDTO:\n");
        sb.append("      type: object\n");
        List<ColumnModel> cols = table.columns();
        // required fields
        StringBuilder required = new StringBuilder();
        for (ColumnModel c : cols) {
            if (!c.nullable() && !(c.primaryKey() && c.autoIncrement())) {
                if (required.length() > 0) required.append(", ");
                required.append(Naming.toCamelCase(c.name()));
            }
        }
        if (required.length() > 0) {
            sb.append("      required: [").append(required).append("]\n");
        }
        sb.append("      properties:\n");
        for (ColumnModel c : cols) {
            if (c.primaryKey() && c.autoIncrement()) continue;
            emitProperty(sb, c);
        }

        sb.append("    ").append(entityName).append("ResponseDTO:\n");
        sb.append("      type: object\n");
        sb.append("      properties:\n");
        for (ColumnModel c : cols) emitProperty(sb, c);
    }

    private void emitProperty(StringBuilder sb, ColumnModel c) {
        sb.append("        ").append(Naming.toCamelCase(c.name())).append(":\n");
        String type = JavaTypeMapper.javaType(c);
        String openApiType = mapToOpenApiType(type);
        sb.append("          type: ").append(openApiType.split("\\|")[0]).append('\n');
        if (openApiType.contains("|")) {
            sb.append("          format: ").append(openApiType.split("\\|")[1]).append('\n');
        }
        if (c.size() > 0 && type.equals("String")) {
            sb.append("          maxLength: ").append(c.size()).append('\n');
        }
        if (!c.comment().isEmpty()) {
            sb.append("          description: ").append(escape(c.comment())).append('\n');
        }
        if (c.isEnum()) {
            sb.append("          enum: [");
            for (int i = 0; i < c.enumValues().size(); i++) {
                if (i > 0) sb.append(", ");
                sb.append('"').append(c.enumValues().get(i)).append('"');
            }
            sb.append("]\n");
        }
    }

    private static String mapToOpenApiType(String javaType) {
        return switch (javaType) {
            case "Boolean" -> "boolean";
            case "Short", "Integer" -> "integer|int32";
            case "Long" -> "integer|int64";
            case "Float" -> "number|float";
            case "Double" -> "number|double";
            case "java.math.BigDecimal" -> "string"; // OpenAPI: string is safest for BigDecimal
            case "java.time.LocalDate" -> "string|date";
            case "java.time.LocalDateTime", "java.time.OffsetDateTime" -> "string|date-time";
            case "java.util.UUID" -> "string|uuid";
            default -> "string";
        };
    }

    private static String escape(String s) {
        return "\"" + s.replace("\"", "\\\"") + "\"";
    }
}
