// Generated by Umaboot. Run `gradle wrapper` once to materialize the wrapper JAR + scripts.
plugins {
    java
<#if springBoot2>
    id("org.springframework.boot") version "${springBootVersion}"
    id("io.spring.dependency-management") version "1.0.15.RELEASE"
<#else>
    id("org.springframework.boot") version "${springBootVersion}"
    id("io.spring.dependency-management") version "1.1.6"
</#if>
<#if isJooq>
    id("nu.studer.jooq") version "<#if springBoot2>8.2<#else>9.0</#if>"
</#if>
}

group = "${projectGroup}"
version = "0.0.1-SNAPSHOT"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(${javaVersion})
    }
}

repositories {
    mavenCentral()
}

<#if isMyBatis>
val mybatisStarterVersion = "<#if springBoot2>2.3.2<#else>3.0.4</#if>"
</#if>

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-validation")
<#if loggingJson>
    implementation("net.logstash.logback:logstash-logback-encoder:7.4")
</#if>
<#if securityEnabled>
    implementation("org.springframework.boot:spring-boot-starter-security")
</#if>
<#if securityJwt>
    implementation("io.jsonwebtoken:jjwt-api:0.11.5")
    runtimeOnly("io.jsonwebtoken:jjwt-impl:0.11.5")
    runtimeOnly("io.jsonwebtoken:jjwt-jackson:0.11.5")
</#if>
<#if openApiAnnotation>
<#if springBoot2>
    implementation("org.springdoc:springdoc-openapi-ui:1.7.0")
<#else>
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0")
</#if>
</#if>
<#if isJpa>
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
<#else>
    implementation("org.springframework.data:spring-data-commons")
</#if>
<#if isMyBatis>
    implementation("org.mybatis.spring.boot:mybatis-spring-boot-starter:${r"$"}mybatisStarterVersion")
    implementation("org.springframework.boot:spring-boot-starter-jdbc")
</#if>
<#if isJooq>
    implementation("org.springframework.boot:spring-boot-starter-jooq")
</#if>
<#if dbIsMariadb>
    runtimeOnly("org.mariadb.jdbc:mariadb-java-client")
<#elseif dbIsMysql>
    runtimeOnly("com.mysql:mysql-connector-j")
<#elseif dbIsSqlserver>
    runtimeOnly("com.microsoft.sqlserver:mssql-jdbc")
<#elseif dbIsSqlite>
    runtimeOnly("org.xerial:sqlite-jdbc")
<#else>
    runtimeOnly("org.postgresql:postgresql")
</#if>
<#if dbIsSqlite && isJpa>
    implementation("org.hibernate.orm:hibernate-community-dialects")
</#if>
<#if useLombok>
    compileOnly("org.projectlombok:lombok")
    annotationProcessor("org.projectlombok:lombok")
</#if>
    testImplementation("org.springframework.boot:spring-boot-starter-test")
<#if testsEnabled && !dbIsSqlite>
    testImplementation("org.testcontainers:junit-jupiter:1.20.4")
    testImplementation("org.testcontainers:<#if dbIsMariadb>mariadb<#elseif dbIsMysql>mysql<#elseif dbIsSqlserver>mssqlserver<#else>postgresql</#if>:1.20.4")
</#if>
<#if isJooq>
    jooqGenerator(<#if dbIsMariadb>"org.mariadb.jdbc:mariadb-java-client:3.4.1"<#elseif dbIsMysql>"com.mysql:mysql-connector-j:8.4.0"<#elseif dbIsSqlserver>"com.microsoft.sqlserver:mssql-jdbc:12.6.4.jre11"<#elseif dbIsSqlite>"org.xerial:sqlite-jdbc:3.47.0.0"<#else>"org.postgresql:postgresql:42.7.4"</#if>)
</#if>
}

tasks.withType<Test> {
    useJUnitPlatform()
}

<#if isJooq>
jooq {
    version.set("<#if springBoot2>3.16.23<#else>3.19.15</#if>")
    edition.set(nu.studer.gradle.jooq.JooqEdition.OSS)
    configurations {
        create("main") {
            generateSchemaSourceOnCompilation.set(true)
            jooqConfiguration.apply {
                jdbc.apply {
                    driver = "${jdbcDriverClass}"
                    url = "${jdbcUrl}"
                    user = "${jdbcUsername}"
                    password = "${jdbcPassword}"
                }
                generator.apply {
                    name = "org.jooq.codegen.JavaGenerator"
                    database.apply {
                        name = "<#if dbIsMariadb>org.jooq.meta.mariadb.MariaDBDatabase<#elseif dbIsMysql>org.jooq.meta.mysql.MySQLDatabase<#elseif dbIsSqlserver>org.jooq.meta.sqlserver.SQLServerDatabase<#elseif dbIsSqlite>org.jooq.meta.sqlite.SQLiteDatabase<#else>org.jooq.meta.postgres.PostgresDatabase</#if>"
                        inputSchema = "${schemaName}"
                    }
                    generate.apply {
                        isPojos = true
                        isDaos = false
                        isRecords = true
                    }
                    target.apply {
                        packageName = "${basePackage}.jooq"
                        directory = "build/generated/jooq/main"
                    }
                }
            }
        }
    }
}
</#if>
